# -*- coding: utf-8 -*-
"""Tarea.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FUkvfGBvmogbs_sb3SAOV2HDm_eBsGKQ
"""

print("      A    \n    A   A \n   AAAAAAA \n  A       A\n A         A\n\n L\n L\n L\n L\n LLLLL\n\n EEEEEE\n E\n EEE\n E\n EEEEEE\n\n  X     X\n   X  X\n    X\n   X  X\n X      X\n\n Y     Y\n  Y   Y\n    Y\n    Y\n    Y\n\n SSSSSSS\nS\n SSSSSSS\n        S\n SSSSSSS")